Events/urls.py
from . import views
from django.urls import path

app_name='Events'
urlpatterns = [
    path('', views.EventsClassView.as_view(), name='Events'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('Itemm/', views.Itemm, name='Itemm'),
    # add item
    path('add',views.CreateItem.as_view(),name='create_item'),
    # update item
    path('update/<int:id>', views.update_item, name='update_item'),
]
 

ThirdEye/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Events/',include('Events.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage,name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    user_name= models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image= models.CharField(max_length=500,default="https://cdn1.vectorstock.com/i/1000x1000/33/30/default-placeholder-avatar-set-profile-vector-21473330.jpg")
    
    
    def get_absolute_url(self):
        return reverse('Events:detail', kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username
    

Events/forms.py
from django import forms 
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model = User
        fields =['username', 'password1', 'password2','email']

Events/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.
def Events(request):
    item_l= Item.objects.all()
    context={
        'item_l': item_l,    
    }
    return render(request, "Event/index.html",context)

class EventsClassView(ListView):
    model = Item;
    template_name= "Event/index.html"
    context_object_name = "item_l" 


def Itemm(request):
    return HttpResponse("<h1>Nawla<h1>")

def detail(request,item_id):
    It=Item.objects.get(pk=item_id)
    context={
        'It':It,
        
    }
    return render (request,'Event/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'Event/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('Events:Events')
    return render(request,'Event/item-form.html',{'form':form})

#this is a class based view for create item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc','item_price', 'item_image']
    template_name = 'Event/item-form.html'
    
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        
        return super().form_valid(form)



def update_item(request,id):
    item= Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('Events:Events')
    return render(request,'Event/item-form.html',{'form':form, 'item':item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.
def register(request):
    if request.method == 'POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user_name=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {user_name},your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})
@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

Events/templates/Event/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
        <link rel="stylesheet" href="{% static 'Event/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <title>Page Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg " style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ThirdEye</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav nav-justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Events:create_item' %}">AddEvents</a>
        </li>
        
        {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
      </ul>
    </div>
  </div>
</nav>
    
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}
        </div>
            
        {% endfor %}
      {% endif %}
    {% block body%}
    {% endblock%}
</body>
</html>

Events/templates/Event/detail.html
{% extends 'Event/base.html' %}

{% block body%}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{object.item_image}}" class="img-thumbnail"/>
        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>${{object.item_price}}</h3>
        </div>
    </div>
</div>

{% endblock %}

Events/templates/Event/index.html
{% extends 'Event/base.html' %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    
</head>
<body>
    {% block body %}
    {% for item in item_l%}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img src="{{item.item_image}}" class="img-thumbnail" alt="...">
            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>${{item.item_price}}</h6>
                <h7>{{ item.user_name }}</h7>
            </div>
            <div class="col-md-2">
                <a href="{% url 'Events:detail' item.id %}" class="btn btn-success">Details</a>
            </div>

        </div>

    {% endfor %}
    {% endblock %}



   
        
    
</body>
</html>

Events/templates/Event/item-form.html
{% extends 'Event/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %} 

                        <button class="btn-info" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'Event/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %} 
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
<h1>You are logged out</h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width ="100px" height="100px" src="{{ user.profile.image.url }}">

users/templates/users/register.html
{% extends 'Event/base.html' %}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor %} 

                        <button class="btn-info" type="submit">SignUp</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}